### ISSUE TITLE
Format string only working if it contains %;

### ISSUE THREAD

**Issue by brandl-muc** [stuartlangridge/gnome-shell-clock-override#22] opened 2018-07-30 19:37 UTC
I'm on Ubuntu 18.04 and I installed clock override both from extensions.gnome.org and the Ubuntu software store.
With both sources I encounter the same issue. The format string is not interpreted correctly with some exceptions:
- Example %H.%M yields %H.%M
- Example 🔔 works
- Example %;cf (emjoi clock face) works
- Example %H %;vf (slow time) works
- Example %FT%T (iso date time) yields %FT%T
- Example %H:%M @%;@. (local and internet time) works
- Example It is %M minutes past hour %H fails
- %% yields %% instead of %
- %F (%a) %;cf %T works
- %F (%a) %;cf %T fails
- %F (%a) %; %T yields the default (same as w/o Clock Override)

So a format string only seems to work if it contains %;* where * denotes something valid as cf or vf. A format string is ignored if it contains any other combination of %;, even if added to a format string that works. All other strings seem to fail, i.e., not interpret the format string.

**Comment by da2x** [comment] 2018-07-30 19:39
Duplicate of #13.

**Comment by brandl-muc** [comment] 2018-07-30 19:39
Oh, sorry
Thanks

**Closed by da2x** 2018-07-30 19:39 UTC
