### ISSUE TITLE
formatting stop working after recent update(25.VI.2018)

### ISSUE THREAD

**Issue by mireczatko** [stuartlangridge/gnome-shell-clock-override#18] opened 2018-07-26 05:28 UTC
after yesterday update, formatting stopped working.
%A %F %T shows exactly as %A %F %T, no conversion to actual date/time

**Comment by taupi** [comment] 2018-07-26 06:06
The fix is in 57fbfc6e20db541a62adfcdda3b9fc936eeeb56c but it wasn't included in the release. I applied the fix manually and then it worked after logging out/in.

**Comment by da2x** [comment] 2018-07-26 09:17
Duplicate of issue #13.

**Closed by da2x** 2018-07-26 09:17 UTC
