### ISSUE TITLE
Clock not working after latest update?

### ISSUE THREAD

**Issue by gurubobnz** [stuartlangridge/gnome-shell-clock-override#20] opened 2018-07-26 20:52 UTC
Hi there,

After the last update my clock's % characters are not being displayed. Sorry I don't know how to check the version that I have.

I am using a custom format as follows:

```
"%d/%m     %H:%M   "
```
I have include the quotes above to show spacing, but they are not part of the format string. This now renders on my screen as that, it is not converted to the current time.

I did find that by including the swatch time I was able to have it work, therefore until this is resolved my format string is as follows:

```
"%d/%m     %H:%M                          %;@"
```

Would appreciate any input.

**Comment by da2x** [comment] 2018-07-26 20:59
Duplicate of #13.

**Closed by da2x** 2018-07-26 20:59 UTC
