### ISSUE TITLE
Displays formatting code rather than clock

### ISSUE THREAD

**Issue by fishears** [stuartlangridge/gnome-shell-clock-override#17] opened 2018-07-25 20:10 UTC
Since the last update from gnome shell extensions website this extension now shows my formatting code where the clock should be e.g. "%r" is displayed rather than the appropriate time formatted. Ubuntu 18.04 Gnome Shell 3.28.2

**Comment by da2x** [comment] 2018-07-25 20:30
Duplicate of #13.

**Closed by da2x** 2018-07-25 20:30 UTC
