### ISSUE TITLE
After update, the format string is shown instead of the time and date

### ISSUE THREAD

**Issue by agreselin** [stuartlangridge/gnome-shell-clock-override#15] opened 2018-07-24 18:20 UTC
Hello, today I was notified of a clock-override update. After updating and rebooting the extension shows the format string instead of the time and date.
I'm using GNOME Shell 3.28.2 on Ubuntu 18.04.

![screenshot from 2018-07-24 20-16-22](https://user-images.githubusercontent.com/22297948/43157953-b6aa9142-8f7e-11e8-96a3-efd9a28a5e10.png)

**Comment by da2x** [comment] 2018-07-24 18:55
Duplicate of issue #13.

**Closed by da2x** 2018-07-24 18:55 UTC
