### ISSUE TITLE
Format string being displayed literally on Fedora 28 after recent update of extension.

### ISSUE THREAD

**Issue by mwbuksas** [stuartlangridge/gnome-shell-clock-override#14] opened 2018-07-24 15:15 UTC
The clock display is showing the format string instead of the formatted time. i.e. "%A, %B %d   %-I:%M %p"

This happened just this morning after updating the extension. I'm on Fedora 28. Gnome version 3.28.2

**Comment by hellysmile** [comment] 2018-07-24 15:19
It seems was fixed by https://github.com/stuartlangridge/gnome-shell-clock-override/commit/57fbfc6e20db541a62adfcdda3b9fc936eeeb56c

@stuartlangridge can You publish new version please?

**Comment by da2x** [comment] 2018-07-24 15:50
This is a duplicate of issue #13.

**Closed by da2x** 2018-07-24 15:50 UTC
